from __future__ import annotations


def emit_gc_support(writer, *, extern_runtime_state: bool = False) -> None:
    w = writer
    w.line("/* ── Mesa GC ─────────────────────────────────────── */")
    w.line("#ifndef MESA_GC_THRESHOLD")
    w.line("#define MESA_GC_THRESHOLD (1024 * 1024)  /* 1MB — collect when heap exceeds this */")
    w.line("#endif")
    w.line()
    w.line("typedef struct Mesa_GC_Obj {")
    w.line("    struct Mesa_GC_Obj* next;  /* intrusive linked list of all allocations */")
    w.line("    void*               base;")
    w.line("    size_t              size;")
    w.line("    int                 mark;")
    w.line("    /* GC descriptor: offset list for pointer fields, terminated by -1 */")
    w.line("    const int*          desc;")
    w.line("} Mesa_GC_Obj;")
    w.line()
    w.line("/* Shadow stack for GC roots */")
    w.line("typedef struct Mesa_GC_Frame {")
    w.line("    struct Mesa_GC_Frame* prev;")
    w.line("    void***               roots;  /* array of pointers-to-pointer */")
    w.line("    int                   count;")
    w.line("} Mesa_GC_Frame;")
    w.line()
    if extern_runtime_state:
        w.line("extern Mesa_GC_Obj* _mesa_gc_head;")
        w.line("extern size_t _mesa_gc_bytes;")
        w.line("extern Mesa_GC_Frame* _mesa_gc_stack;")
    else:
        w.line("static Mesa_GC_Obj*   _mesa_gc_head   = NULL;")
        w.line("static size_t         _mesa_gc_bytes  = 0;")
        w.line("static Mesa_GC_Frame* _mesa_gc_stack  = NULL;")
    w.line()
    w.line("static const int _mesa_gc_desc_none[] = {-1};")
    w.line()
    w.line("static void mesa_gc_push(Mesa_GC_Frame* f, void*** roots, int count) {")
    w.line("    f->roots = roots;")
    w.line("    f->count = count;")
    w.line("    f->prev = _mesa_gc_stack;")
    w.line("    _mesa_gc_stack = f;")
    w.line("}")
    w.line("static void mesa_gc_pop(void) {")
    w.line("    if (_mesa_gc_stack) _mesa_gc_stack = _mesa_gc_stack->prev;")
    w.line("}")
    w.line()
    w.line("static Mesa_GC_Obj* mesa_gc_find_obj(void* ptr) {")
    w.line("    if (!ptr) return NULL;")
    w.line("    for (Mesa_GC_Obj* obj = _mesa_gc_head; obj; obj = obj->next) {")
    w.line("        if ((void*)(obj + 1) == ptr) return obj;")
    w.line("    }")
    w.line("    return NULL;")
    w.line("}")
    w.line()
    w.line("static void mesa_gc_mark(Mesa_GC_Obj* obj);")
    w.line("static void mesa_gc_mark_ptr(void* ptr) {")
    w.line("    Mesa_GC_Obj* obj = mesa_gc_find_obj(ptr);")
    w.line("    if (obj) mesa_gc_mark(obj);")
    w.line("}")
    w.line()
    w.line("static void mesa_gc_mark(Mesa_GC_Obj* obj) {")
    w.line("    if (!obj || obj->mark) return;")
    w.line("    obj->mark = 1;")
    w.line("    if (!obj->desc) return;")
    w.line("    char* base = (char*)(obj + 1);")
    w.line("    for (int i = 0; obj->desc[i] >= 0; i++) {")
    w.line("        void* child = *(void**)(base + obj->desc[i]);")
    w.line("        mesa_gc_mark_ptr(child);")
    w.line("    }")
    w.line("}")
    w.line()
    w.line("static void mesa_gc_collect(void) {")
    w.line("    Mesa_GC_Frame* f = _mesa_gc_stack;")
    w.line("    while (f) {")
    w.line("        for (int i = 0; i < f->count; i++) {")
    w.line("            void* p = *f->roots[i];")
    w.line("            mesa_gc_mark_ptr(p);")
    w.line("        }")
    w.line("        f = f->prev;")
    w.line("    }")
    w.line("    Mesa_GC_Obj** cur = &_mesa_gc_head;")
    w.line("    while (*cur) {")
    w.line("        if (!(*cur)->mark) {")
    w.line("            Mesa_GC_Obj* dead = *cur;")
    w.line("            *cur = dead->next;")
    w.line("            _mesa_gc_bytes -= dead->size;")
    w.line("            free(dead->base);")
    w.line("        } else {")
    w.line("            (*cur)->mark = 0;")
    w.line("            cur = &(*cur)->next;")
    w.line("        }")
    w.line("    }")
    w.line("}")
    w.line()
    w.line("static void* mesa_gc_alloc(size_t size, size_t align, const int* desc) {")
    w.line("    if (_mesa_gc_bytes + size > MESA_GC_THRESHOLD) mesa_gc_collect();")
    w.line("    size_t actual_align = align > sizeof(void*) ? align : sizeof(void*);")
    w.line("    size_t total = sizeof(Mesa_GC_Obj) + size + actual_align - 1;")
    w.line("    char* raw = (char*)malloc(total);")
    w.line('    if (!raw) { fprintf(stderr, "GC: out of memory\\n"); abort(); }')
    w.line("    uintptr_t payload_addr = ((uintptr_t)(raw + sizeof(Mesa_GC_Obj) + actual_align - 1)) & ~((uintptr_t)actual_align - 1);")
    w.line("    Mesa_GC_Obj* obj = (Mesa_GC_Obj*)(payload_addr - sizeof(Mesa_GC_Obj));")
    w.line("    obj->next = _mesa_gc_head;")
    w.line("    obj->base = raw;")
    w.line("    obj->size = size;")
    w.line("    obj->mark = 0;")
    w.line("    obj->desc = desc;")
    w.line("    _mesa_gc_head = obj;")
    w.line("    _mesa_gc_bytes += size;")
    w.line("    memset((void*)payload_addr, 0, size);")
    w.line("    return (void*)payload_addr;")
    w.line("}")
    w.line()
    w.line("/* ── Ambient allocator stack for esc ────────────── */")
    w.line("typedef struct {")
    w.line("    void* self;")
    w.line("    void* (*alloc)(void* self, size_t size, size_t align);")
    w.line("} Mesa_AllocContext;")
    w.line()
    if extern_runtime_state:
        w.line("extern Mesa_AllocContext _mesa_alloc_stack[256];")
        w.line("extern int _mesa_alloc_stack_len;")
    else:
        w.line("static Mesa_AllocContext _mesa_alloc_stack[256] = {{0}};")
        w.line("static int _mesa_alloc_stack_len = 0;")
    w.line()
    w.line("static void mesa_allocctx_push(void* self, void* (*alloc)(void* self, size_t size, size_t align)) {")
    w.line("    if (_mesa_alloc_stack_len >= 256) {")
    w.line('        fprintf(stderr, "allocator context stack overflow\\n");')
    w.line("        abort();")
    w.line("    }")
    w.line("    _mesa_alloc_stack[_mesa_alloc_stack_len++] = (Mesa_AllocContext){.self = self, .alloc = alloc};")
    w.line("}")
    w.line("static void mesa_allocctx_pop(void) {")
    w.line("    if (_mesa_alloc_stack_len > 0) _mesa_alloc_stack_len--;")
    w.line("}")
    w.line("static Mesa_AllocContext* mesa_allocctx_escape_target(void) {")
    w.line("    if (_mesa_alloc_stack_len >= 2) return &_mesa_alloc_stack[_mesa_alloc_stack_len - 2];")
    w.line("    if (_mesa_alloc_stack_len == 1) return &_mesa_alloc_stack[0];")
    w.line("    return NULL;")
    w.line("}")
    w.line("static void* mesa_allocctx_alloc(Mesa_AllocContext* c, size_t size, size_t align) {")
    w.line("    if (!c || !c->alloc) return mesa_c_alloc((int64_t)size, (int64_t)align);")
    w.line("    return c->alloc(c->self, size, align);")
    w.line("}")
    w.line()


def emit_gc_runtime_state(writer) -> None:
    w = writer
    w.line("Mesa_GC_Obj* _mesa_gc_head = NULL;")
    w.line("size_t _mesa_gc_bytes = 0;")
    w.line("Mesa_GC_Frame* _mesa_gc_stack = NULL;")
    w.line("Mesa_AllocContext _mesa_alloc_stack[256] = {{0}};")
    w.line("int _mesa_alloc_stack_len = 0;")
